name: pcf-checkout-service
path: build/libs/pcf-checkout-service-0.0.1-SNAPSHOT.jar
buildpack: https://github.com/cloudfoundry/java-buildpack.git
memory: 1G
port: 8005
spring:
  security:
    user:
      name: ${vcap.services.myUserProvidedCupsService.credentials.username}
      password: ${vcap.service.myUserProvidedCupsService.credentials.password}

services:
  - myEurekaServiceRegistry
  - myUserProvidedCupsService
  - pcflogs
